### ISSUE TITLE
[bug] HttpError: Not Found

### ISSUE THREAD

**Issue by codebydant** [rexdefuror/check_artifact_exists#1]
## Description

```yml
- name: Check if artifact exists
  id: artifact-exists
  uses: rexdefuror/check_artifact_exists@v1.0.1
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    owner: ${{ github.repository_owner }}
    repo: ${{ github.repository.name }}
    name: Terraform Artifact ${{ inputs.project-name }}-${{ inputs.environment-name }}

- name: echo
  run: |
    echo "other: ${{ env.ARTIFACT_EXISTS }}"
```

## logs

```bash
HttpError: Not Found
    at /home/runner/work/_actions/rexdefuror/check_artifact_exists/v1.0.1/webpack:/check_artifact_exists/node_modules/@octokit/request/dist-node/index.js:86:1
    at process.artifact (node:internal/process/task_queues:96:5)
    at main (/home/runner/work/_actions/rexdefuror/check_artifact_exists/v1.0.1/webpack:/check_artifact_exists/lib/index.js:[12](https://github.com/org/repo/actions/runs/5647415825/job/15297487051#step:4:13):1)
```
